### ISSUE TITLE
tf_records_end_to_end hang in tensorflow 1.4?

### ISSUE THREAD

**Issue by fancyerii** [Hezi-Resheff/Oreilly-Learning-TensorFlow#10]
When I run tf_records_end_to_end.py, it hangs in line 101 sess.run([train_op])

**Comment by foohyfooh** [comment]
The code is missing the following line from the book in after coord = tf.train.Coordinator()
```
threads = tf.train.start_queue_runners(sess=sess,coord=coord)
```

and these after the finally block
```
# Wait for threads to finish
coord.join(threads)
sess.close()
```

I using TensorFlow 1.7, and hopefully these lines are all you need to solve the problem. If not I recommend upgrading your version of TensorFlow, if possible.
