### ISSUE TITLE
Jupyter Notebooks

### ISSUE THREAD

**Issue by foohyfooh** [Hezi-Resheff/Oreilly-Learning-TensorFlow#14]
- Run the notebooks for Chapters 7 and 10 similar to how Chapter 3's notebooks was run so that people can see the expected output.
- Some of the constants are defined in cells that they do not relate to and thus in the cells that they are for there is missing information. This makes it hard to understand the code since some of the data is missing from the cells related to specific tasks.
- Side Note: Convert some of the existing Python files to Jupyter Notebooks to make it easier for someone to look at the code and see the output of different sections similar to how it is done in the book.

**Comment by Hezi-Resheff** [comment]
Thanks for the feedback.
