### ISSUE TITLE
chapter 4, mnist_cnn

### ISSUE THREAD

**Issue by micoing** [Hezi-Resheff/Oreilly-Learning-TensorFlow#17]
Hi, I have learned deep learning & machine learning with provided codes. 
However, when i studied the convolutional_neural_network mnist example(code name mnist_cnn ) in chapter 4, occur the same accuracy. is it possible to occur the same accuracy?  Likewise, i start again the mnist example, it also occurs  training accuracy same to prior practiced.
![same training accuracy](https://user-images.githubusercontent.com/42015885/45604284-c7bc2d00-ba6d-11e8-98c2-a3db422d795a.PNG)

**Comment by Hezi-Resheff** [comment]
It looks like you have an issue with a constant random seed.
