### ISSUE TITLE
BUG: chapter 6

### ISSUE THREAD

**Issue by zhan4402** [Hezi-Resheff/Oreilly-Learning-TensorFlow#3]
loss = tf.reduce_mean(
  tf.nn.nce_loss(nce_weights, nce_biases, embed, train_labels,
                 negative_samples, vocabulary_size))

This line returns the following error. 
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("nce_loss/Reshape_1:0", shape=(?, 1, ?), dtype=float32)'

**Comment by ttthhh** [comment]
Please run the new code in the chapter 6 folder, and check it out again.
